spring:
  cache:
    ehcache:
      config: classpath:ehcache.xml
figi:
    searchUrl: https://api.openfigi.com/v3/search
    key: e32a66e4-9f44-45b9-b58a-4070fd866078000==
    header: X-OPENFIGI-APIKEY
    
resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 5
            minimumNumberOfCalls: 3
            permittedNumberOfCallsInHalfOpenState: 2
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 10s
            failureRateThreshold: 50
            eventConsumerBufferSize: 5
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - org.springframework.http.converter.HttpMessageNotReadableException
                - java.io.IOException
            ignoreExceptions:
                - java.lang.NumberFormatException
    instances:
        backendA:
            baseConfig: default
resilience4j.retry:
    configs:
        default:
            maxAttempts: 2
            waitDuration: 100
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - org.springframework.http.converter.HttpMessageNotReadableException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
            ignoreExceptions:
                - java.lang.NumberFormatException
    instances:
        backendA:
            baseConfig: default